# Generated by Django 4.2.9 on 2024-05-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allorders",
            name="foods_order_bill",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="allorders",
            name="phone",
            field=models.CharField(default="", max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="allorders",
            name="room_order_bill",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
