# Generated by Django 4.2.9 on 2024-05-30 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0002_alter_allorders_foods_order_bill_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="AllOrders",),
    ]
